import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { Save, Plus, X, Palette, Users, Target, Sparkles } from "lucide-react";

export interface BrandKitData {
  id: string;
  brandName: string;
  logo?: string;
  colors: {
    primary: string;
    secondary: string;
    accent: string;
  };
  fonts: {
    display: string;
    body: string;
  };
  tone: string;
  voice: string;
  tagline: string;
  targetAudience: string[];
  competitors: string[];
  excludeCompetitors: string[];
  keywords: string[];
  socialHandles: Record<string, string>;
  aboutBrand: string;
}

export function BrandKitManager({
  brandKit,
  onSave,
  onClose,
}: {
  brandKit?: BrandKitData;
  onSave: (kit: BrandKitData) => void;
  onClose: () => void;
}) {
  const [data, setData] = useState<BrandKitData>(
    brandKit || {
      id: Date.now().toString(),
      brandName: "",
      colors: { primary: "#0052FF", secondary: "#E5E9F2", accent: "#00C853" },
      fonts: { display: "Sora", body: "Inter" },
      tone: "",
      voice: "",
      tagline: "",
      targetAudience: [],
      competitors: [],
      excludeCompetitors: [],
      keywords: [],
      socialHandles: {},
      aboutBrand: "",
    }
  );

  const [newAudience, setNewAudience] = useState("");
  const [newCompetitor, setNewCompetitor] = useState("");
  const [newKeyword, setNewKeyword] = useState("");

  const handleSave = () => {
    if (!data.brandName.trim()) {
      toast.error("Brand name is required");
      return;
    }

    onSave(data);
    toast.success("Brand Kit saved and will be injected into all content!");
    onClose();
  };

  const addAudience = () => {
    if (newAudience.trim() && !data.targetAudience.includes(newAudience)) {
      setData(prev => ({
        ...prev,
        targetAudience: [...prev.targetAudience, newAudience],
      }));
      setNewAudience("");
    }
  };

  const addCompetitor = () => {
    if (newCompetitor.trim() && !data.competitors.includes(newCompetitor)) {
      setData(prev => ({
        ...prev,
        competitors: [...prev.competitors, newCompetitor],
      }));
      setNewCompetitor("");
    }
  };

  const addKeyword = () => {
    if (newKeyword.trim() && !data.keywords.includes(newKeyword)) {
      setData(prev => ({
        ...prev,
        keywords: [...prev.keywords, newKeyword],
      }));
      setNewKeyword("");
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 p-4 py-12">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <div>
            <h1 className="text-3xl font-bold text-slate-900">Brand Kit</h1>
            <p className="text-slate-600 mt-1">
              This is injected into every asset generated by ARIA
            </p>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-slate-200 rounded-lg transition"
          >
            <X className="w-6 h-6 text-slate-600" />
          </button>
        </div>

        <div className="grid grid-cols-3 gap-6 mb-8">
          {/* Core Brand Info */}
          <Card className="col-span-3 lg:col-span-2 p-8 border-0 shadow-lg">
            <h2 className="text-xl font-bold text-slate-900 mb-6 flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-blue-600" />
              Core Information
            </h2>

            <div className="space-y-4 mb-6">
              <div>
                <label className="block text-sm font-semibold text-slate-900 mb-2">
                  Brand Name
                </label>
                <Input
                  value={data.brandName}
                  onChange={e => setData(prev => ({ ...prev, brandName: e.target.value }))}
                  placeholder="Your brand name"
                  className="border-slate-300"
                />
              </div>

              <div>
                <label className="block text-sm font-semibold text-slate-900 mb-2">
                  Tagline
                </label>
                <Input
                  value={data.tagline}
                  onChange={e => setData(prev => ({ ...prev, tagline: e.target.value }))}
                  placeholder="Your unique value proposition"
                  className="border-slate-300"
                />
              </div>

              <div>
                <label className="block text-sm font-semibold text-slate-900 mb-2">
                  Brand Story (About)
                </label>
                <Textarea
                  value={data.aboutBrand}
                  onChange={e => setData(prev => ({ ...prev, aboutBrand: e.target.value }))}
                  placeholder="Tell the story of your brand..."
                  className="h-24 border-slate-300"
                />
              </div>
            </div>

            {/* Tone & Voice */}
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-semibold text-slate-900 mb-2">
                  Brand Tone
                </label>
                <Input
                  value={data.tone}
                  onChange={e => setData(prev => ({ ...prev, tone: e.target.value }))}
                  placeholder="e.g., Professional, Playful, Warm, Authoritative"
                  className="border-slate-300"
                />
                <p className="text-xs text-slate-500 mt-1">
                  How should ARIA sound when representing your brand?
                </p>
              </div>

              <div>
                <label className="block text-sm font-semibold text-slate-900 mb-2">
                  Brand Voice
                </label>
                <Input
                  value={data.voice}
                  onChange={e => setData(prev => ({ ...prev, voice: e.target.value }))}
                  placeholder="e.g., Conversational, Technical, Inspirational"
                  className="border-slate-300"
                />
                <p className="text-xs text-slate-500 mt-1">
                  The personality behind your writing
                </p>
              </div>
            </div>
          </Card>

          {/* Visual Identity */}
          <Card className="p-8 border-0 shadow-lg">
            <h2 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
              <Palette className="w-5 h-5 text-blue-600" />
              Colors
            </h2>

            <div className="space-y-3">
              <div>
                <label className="text-xs font-semibold text-slate-700 mb-1 block">
                  Primary
                </label>
                <div className="flex gap-2 items-center">
                  <input
                    type="color"
                    value={data.colors.primary}
                    onChange={e =>
                      setData(prev => ({
                        ...prev,
                        colors: { ...prev.colors, primary: e.target.value },
                      }))
                    }
                    className="w-12 h-12 rounded cursor-pointer"
                  />
                  <input
                    type="text"
                    value={data.colors.primary}
                    onChange={e =>
                      setData(prev => ({
                        ...prev,
                        colors: { ...prev.colors, primary: e.target.value },
                      }))
                    }
                    className="flex-1 text-xs border border-slate-300 rounded px-2 py-1"
                  />
                </div>
              </div>

              <div>
                <label className="text-xs font-semibold text-slate-700 mb-1 block">
                  Secondary
                </label>
                <div className="flex gap-2 items-center">
                  <input
                    type="color"
                    value={data.colors.secondary}
                    onChange={e =>
                      setData(prev => ({
                        ...prev,
                        colors: { ...prev.colors, secondary: e.target.value },
                      }))
                    }
                    className="w-12 h-12 rounded cursor-pointer"
                  />
                  <input
                    type="text"
                    value={data.colors.secondary}
                    onChange={e =>
                      setData(prev => ({
                        ...prev,
                        colors: { ...prev.colors, secondary: e.target.value },
                      }))
                    }
                    className="flex-1 text-xs border border-slate-300 rounded px-2 py-1"
                  />
                </div>
              </div>

              <div>
                <label className="text-xs font-semibold text-slate-700 mb-1 block">
                  Accent
                </label>
                <div className="flex gap-2 items-center">
                  <input
                    type="color"
                    value={data.colors.accent}
                    onChange={e =>
                      setData(prev => ({
                        ...prev,
                        colors: { ...prev.colors, accent: e.target.value },
                      }))
                    }
                    className="w-12 h-12 rounded cursor-pointer"
                  />
                  <input
                    type="text"
                    value={data.colors.accent}
                    onChange={e =>
                      setData(prev => ({
                        ...prev,
                        colors: { ...prev.colors, accent: e.target.value },
                      }))
                    }
                    className="flex-1 text-xs border border-slate-300 rounded px-2 py-1"
                  />
                </div>
              </div>
            </div>
          </Card>
        </div>

        {/* Audience, Competitors, Keywords */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8">
          {/* Target Audience */}
          <Card className="p-6 border-0 shadow-lg">
            <h3 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
              <Users className="w-5 h-5 text-blue-600" />
              Target Audience
            </h3>

            <div className="space-y-2 mb-4">
              {data.targetAudience.map((aud, i) => (
                <Badge key={i} variant="secondary" className="flex items-center gap-2 px-3 py-1">
                  {aud}
                  <button
                    onClick={() =>
                      setData(prev => ({
                        ...prev,
                        targetAudience: prev.targetAudience.filter((_, idx) => idx !== i),
                      }))
                    }
                    className="ml-1"
                  >
                    ×
                  </button>
                </Badge>
              ))}
            </div>

            <div className="flex gap-1">
              <Input
                value={newAudience}
                onChange={e => setNewAudience(e.target.value)}
                onKeyPress={e => e.key === "Enter" && addAudience()}
                placeholder="Add audience"
                className="text-xs border-slate-300"
              />
              <Button onClick={addAudience} size="sm" variant="outline">
                <Plus className="w-3 h-3" />
              </Button>
            </div>
          </Card>

          {/* Competitors */}
          <Card className="p-6 border-0 shadow-lg">
            <h3 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
              <Target className="w-5 h-5 text-blue-600" />
              Key Competitors
            </h3>

            <div className="space-y-2 mb-4">
              {data.competitors.map((comp, i) => (
                <Badge key={i} variant="secondary" className="flex items-center gap-2 px-3 py-1">
                  {comp}
                  <button
                    onClick={() =>
                      setData(prev => ({
                        ...prev,
                        competitors: prev.competitors.filter((_, idx) => idx !== i),
                      }))
                    }
                    className="ml-1"
                  >
                    ×
                  </button>
                </Badge>
              ))}
            </div>

            <div className="flex gap-1">
              <Input
                value={newCompetitor}
                onChange={e => setNewCompetitor(e.target.value)}
                onKeyPress={e => e.key === "Enter" && addCompetitor()}
                placeholder="Add competitor"
                className="text-xs border-slate-300"
              />
              <Button onClick={addCompetitor} size="sm" variant="outline">
                <Plus className="w-3 h-3" />
              </Button>
            </div>
          </Card>

          {/* Keywords */}
          <Card className="p-6 border-0 shadow-lg">
            <h3 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-blue-600" />
              Brand Keywords
            </h3>

            <div className="space-y-2 mb-4">
              {data.keywords.map((kw, i) => (
                <Badge key={i} variant="secondary" className="flex items-center gap-2 px-3 py-1">
                  {kw}
                  <button
                    onClick={() =>
                      setData(prev => ({
                        ...prev,
                        keywords: prev.keywords.filter((_, idx) => idx !== i),
                      }))
                    }
                    className="ml-1"
                  >
                    ×
                  </button>
                </Badge>
              ))}
            </div>

            <div className="flex gap-1">
              <Input
                value={newKeyword}
                onChange={e => setNewKeyword(e.target.value)}
                onKeyPress={e => e.key === "Enter" && addKeyword()}
                placeholder="Add keyword"
                className="text-xs border-slate-300"
              />
              <Button onClick={addKeyword} size="sm" variant="outline">
                <Plus className="w-3 h-3" />
              </Button>
            </div>
          </Card>
        </div>

        {/* Save Button */}
        <div className="flex gap-3">
          <Button
            onClick={handleSave}
            className="flex-1 h-12 bg-blue-600 hover:bg-blue-700 font-semibold text-base"
          >
            <Save className="w-5 h-5 mr-2" />
            Save Brand Kit
          </Button>

          <Button
            onClick={onClose}
            variant="outline"
            className="h-12 border-slate-300 font-semibold"
          >
            Cancel
          </Button>
        </div>

        {/* Info */}
        <div className="mt-6 p-4 bg-blue-50 border border-blue-200 rounded-lg">
          <p className="text-sm text-blue-900">
            <strong>✓ Auto-injected:</strong> This Brand Kit will automatically be included in the prompt for every asset generated. No need to reference it manually.
          </p>
        </div>
      </div>
    </div>
  );
}
